export enum HttpStatusCode {
    Continue = 100, // 继续。客户端应继续其请求
    SwitchingProtocols = 101, // 协议切换。服务器根据客户端的请求切换协议
    OK = 200, // 正常。请求已成功处理
    Created = 201, // 已创建。请求已经被实现，而且有一个新的资源已经依据请求的需要而创建
    Accepted = 202, // 已接受。服务器已接受请求，但尚未处理
    NonAuthoritativeInformation = 203, // 非授权信息。请求成功。但返回的元信息在缓存中取得，因此不是来自源服务器的资源
    NoContent = 204, // 无内容。服务器成功处理，但未返回内容
    ResetContent = 205, // 重置内容。服务器处理成功，用户终端（例如：浏览器）应重置文档视图
    PartialContent = 206, // 部分内容。服务器成功处理了部分 GET 请求
    MultipleChoices = 300, // 多种选择。请求的资源可包括多个位置，相应可返回指示哪个位置更合适的一组链接条件
    MovedPermanently = 301, // 永久移动。请求的资源已被永久移动到新 URI，返回信息会包括新的 URI
    Found = 302, // 临时移动。请求的资源临时从不同的 URI响应请求，但未来任何更新的请求仍应使用原始 URI
    SeeOther = 303, // 查看其它地址。对应当前请求的响应可以在另一个 URI 上被找到，客户端应该使用 GET 方法去获取请求的资源
    NotModified = 304, // 未修改。自上次请求后，请求的资源未修改过。服务器返回此响应时，不会返回资源的内容
    UseProxy = 305, // 使用代理。所请求的资源必须通过代理访问
    TemporaryRedirect = 307, // 临时重定向。请求的资源临时从不同的 URI 响应请求
    PermanentRedirect = 308, // 永久重定向。请求的资源已被永久移动到新 URI，客户端应使用新的 URI 访问
    BadRequest = 400, // 错误请求。服务器不理解请求的语法
    Unauthorized = 401, // 未授权。请求要求身份验证。对于需要登录的网页，服务器可能返回此响应
    PaymentRequired = 402, // 需要付款。预留状态。以后可能会使用
    Forbidden = 403, // 禁止访问。服务器拒绝请求
    NotFound = 404, // 未找到。服务器找不到请求的资源。例如，不存在的文件或目录
    MethodNotAllowed = 405, // 方法禁用。禁用请求中指定的方法
    NotAcceptable = 406, // 不接受。无法使用请求的内容特性响应请求的资源状态
    ProxyAuthenticationRequired = 407, // 需要代理身份验证。客户端必须先使用代理对自己进行身份验证
    RequestTimeout = 408, // 请求超时。服务器等候请求时发生超时
    Conflict = 409, // 冲突。服务器在完成请求时发生冲突，返回此状态码可以帮助解决错误
    Gone = 410, // 已删除。请求的资源已被永久删除，且不会再得到的
    LengthRequired = 411, // 需要有效长度。服务器不接受不含有效内容长度标头字段的请求
    PreconditionFailed = 412, // 先决条件错误。服务器未满足请求者在请求中设置的其中一个前提条件
    PayloadTooLarge = 413, // 负载过大。请求实体过大，服务器无法处理
    URITooLong = 414, // URI 过长。请求的 URI 长度超过服务器能够解释的长度，因此服务器拒绝对该请求提供服务
    UnsupportedMediaType = 415, // 不支持的媒体类型。请求的格式不受请求页面的支持
    RangeNotSatisfiable = 416, // 范围不符合要求。服务器无法满足 Range 头指定的所有范围
    ExpectationFailed = 417, // 执行失败。服务器未满足期望请求标头字段的要求
    ImATeapot = 418, // 我是茶壶。当一个请求不能被处理，因为它是一个彻底的怪异请求。
    MisdirectedRequest = 421, // 请求错误。由于请求头中指定了一个或多个不正确的参数，服务器不能或不会处理该请求
    UnprocessableEntity = 422, // 不可处理的实体。请求格式正确，但是由于含有语义错误，无法响应
    Locked = 423, // 已锁定。当前资源被锁定
    FailedDependency = 424, // 依赖关系错误。请求失败，由于先前的请求失败，导致这个请求失败
    TooEarly = 425, // 过早。服务器不愿意冒险去处理可能重播的请求
    UpgradeRequired = 426, // 需要升级。客户端应当切换到TLS/1.0
    PreconditionRequired = 428, // 先决条件要求。原始服务器要求该请求满足一个或多个先决条件
    TooManyRequests = 429, // 请求过多。用户在给定的时间内发送了太多请求
    RequestHeaderFieldsTooLarge = 431, // 请求头字段过大。服务器不愿意处理该请求，因为某些请求头字段超过了服务器要求或者限制的大小
    UnavailableForLegalReasons = 451, // 由于法律原因不可用。用户请求非法资源，例如：Web 页面上的内容被屏蔽
    InternalServerError = 500, // 内部服务器错误。服务器遇到错误，无法完成请求
    NotImplemented = 501, // 未实现。服务器不支持请求的功能，无法完成请求
    BadGateway = 502, // 错误网关。服务器作为网关或代理，从上游服务器收到无效响应
    ServiceUnavailable = 503, // 服务不可用。目前服务器不可用（由于超载或停机维护）。通常，这只是暂时状态
    GatewayTimeout = 504, // 网关超时。服务器作为网关或代理，但是没有及时从上游服务器收到请求
    HTTPVersionNotSupported = 505, // HTTP 版本不受支持。服务器不支持请求中所用的 HTTP 协议版本
    VariantAlsoNegotiates = 506, // 内容协商失败。服务器有一个内部配置错误：对请求的透明内容协商导致循环引用
    InsufficientStorage = 507, // 存储空间不足。服务器无法存储完成请求所必须的内容
    LoopDetected = 508, // 检测到循环。服务器检测到无限循环请求
    NotExtended = 510, // 扩展未实现。获取资源所需的策略没有被满足
    NetworkAuthenticationRequired = 511 // 需要网络身份验证。客户端需要对付未授权访问所需的身份验证信息
}